name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch: # also allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          server: 82.180.172.230
          username: u285963410
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /new/
          dangerous-clean-slate: false
          state-name: .ftp-sync-state-v2.json
          exclude: |
            **/.git*
            **/.git*/**
            **/protected-docs/**
            **/config.php
